// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3qqOs-Q6GEzj67kcZ7ynq1R5UBDzyKY',
    appId: '1:364481453416:web:075a577d7e9e399b75cadd',
    messagingSenderId: '364481453416',
    projectId: 'is3-proyecto',
    authDomain: 'is3-proyecto.firebaseapp.com',
    storageBucket: 'is3-proyecto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnaqgb-m3YQXX-V4UonrsB1E87U9U2KPs',
    appId: '1:364481453416:android:8f659f0e3ad7bd7b75cadd',
    messagingSenderId: '364481453416',
    projectId: 'is3-proyecto',
    storageBucket: 'is3-proyecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABHPiIxkzSkX498bT1hw-BSwLyHb-Hyv0',
    appId: '1:364481453416:ios:60f49b65815cf49775cadd',
    messagingSenderId: '364481453416',
    projectId: 'is3-proyecto',
    storageBucket: 'is3-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABHPiIxkzSkX498bT1hw-BSwLyHb-Hyv0',
    appId: '1:364481453416:ios:60f49b65815cf49775cadd',
    messagingSenderId: '364481453416',
    projectId: 'is3-proyecto',
    storageBucket: 'is3-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz3qqOs-Q6GEzj67kcZ7ynq1R5UBDzyKY',
    appId: '1:364481453416:web:0a17ced2b8a75c0875cadd',
    messagingSenderId: '364481453416',
    projectId: 'is3-proyecto',
    authDomain: 'is3-proyecto.firebaseapp.com',
    storageBucket: 'is3-proyecto.firebasestorage.app',
  );
}
